- name: deploy webserver
  hosts: all
  user: root
  become: true
  tasks:
  - name: install httpd
    yum:
     name: httpd
     state: latest
 
  - name: check file stat
    stat:
     path: /var/www/html/index.html
    register: abc
  
  - name: create  index.html
    copy:
     content: "{{ ansible_os_family }}" 
     dest: /var/www/html/index.html
    when: abc.stat.exists  == false 

  - name: append  index.html
    lineinfile:
     line: "{{ ansible_os_family }}" 
     dest: /var/www/html/index.html
    when: abc.stat.exists  == true



 
  - name: start and enable httpd
    service:
     name: httpd
     state: started
     enabled: true
